name: nightly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '18 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - run: |
          pwd
          git clone https://github.com/hashicorp/nomad-driver-podman build
          cd build
          CGO_ENABLED=0 go build .
          strip nomad-driver-podman
          mv nomad-driver-podman ..
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: nomad-driver-podman
